ti-j72xx: ti-rtos-firmware: replace hardcode "lib" with variable "nonarch_base_libdir"
Issue: LIN1021-3247

If the os-tree feature is enabled for this BSP, the "/lib" path will have
prefix "/usr/" and caused below building error. Replace the hardcode "/lib" directory
with variable "nonarch_base_libdir".

Fix below building error:
ERROR: ti-rtos-firmware-08.01.00.02-r1.0 do_package: QA Issue:
ti-rtos-firmware: Files/directories were installed but not shipped in any package:
/lib
/lib/firmware
/lib/firmware/ethfw
/lib/firmware/pdk-ipc
/lib/firmware/ethfw/app_remoteswitchcfg_server_strip.xer5f
/lib/firmware/pdk-ipc/ipc_echo_test_mcu1_1_release_strip.xer5f
/lib/firmware/pdk-ipc/ipc_echo_test_mcu3_0_release_strip.xer5f
/lib/firmware/pdk-ipc/ipc_echo_testb_mcu1_0_release_strip.xer5f
/lib/firmware/pdk-ipc/ipc_echo_test_mcu2_0_release_strip.xer5f
/lib/firmware/pdk-ipc/ipc_echo_test_c66xdsp_2_release_strip.xe66
/lib/firmware/pdk-ipc/ipc_echo_test_c7x_1_release_strip.xe71
/lib/firmware/pdk-ipc/ipc_echo_test_c66xdsp_1_release_strip.xe66
/lib/firmware/pdk-ipc/ipc_echo_test_mcu2_1_release_strip.xer5f
/lib/firmware/pdk-ipc/ipc_echo_test_mcu3_1_release_strip.xer5f
Please set FILES such that these items are packaged. Alternatively if they are unneeded,
avoid installing them or delete them within do_install.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>